name: CurseForge Release

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to use Node.js 20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the addon
        run: npm run build

      - name: Create CurseForge zip
        run: |
          mkdir -p release
          zip -r release/bento_interface.zip * -x '*.git*' 'node_modules/*' '.github/*'

      - name: Read README.md
        id: readme
        run: |
          echo "content<<EOF" >> $GITHUB_ENV
          cat README.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload to CurseForge
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          README_CONTENT: ${{ env.content }}
        run: |
          curl -X POST "https://wow.curseforge.com/api/projects/1044952/upload-file" \
            -H "x-api-token: $CF_API_KEY" \
            -F "file=@release/bento_interface.zip" \
            -F "metadata={\"changelog\": \"New release\", \"displayName\": \"Bento Interface 1.0\", \"description\": \"${README_CONTENT}\"}"
